### ISSUE TITLE
Feat request: Option to use ammo icons as labels

### ISSUE THREAD

**Issue by mcauley-penney** [Tekkish/AmmoInfo#1]
### What
I'd like to be able to label my ammo with the sprites used for each ammo type in-game (see the image at bottom). I am not interested in changing anything else; just adding the ammo sprites in front of the ammo value text that already exists.

### Context
I autoload most of the Simple HUD mods. They're unobtrusive and I like that I can position them anywhere because I like health and ammo information pretty close to the center of the screen. This keeps the distance I have to look away pretty short, reducing cognitive load or reaction time. To this end, I think that having the option to use ammo icons as labels for ammo would be useful.

### Why
Sometimes the player must or wants to change weapons mid-encounter and knowing which weapons have ammo is useful. While the labels are already pretty minimal, I'd argue icons are even more minimal (despite appearing less so) because they reduce the amount of reading that one has to do. Using abbreviations and coloring is also useful (a red, single letter is essentially an icon), but using the visual language that the game already uses is arguably more recognizable and standard. 

### Examples
This is already how other displays, such as GZDoom's Alternative HUD (see below) and [Dae's Fullscreen HUD](https://forum.zdoom.org/viewtopic.php?t=76876), just for one example, work. Why not use these? They do not have configurable positioning nor do they allow you to use only the ammo information; they both require that you also have health information on the screen, taking up screen real estate and providing information I like to get from Simple HUD's playerinfo.

### Contribution
I'm a neophyte with Doom scripting; I don't know ACS well, though I'm learning it right now while trying to implement this feature. I've already taken a look at the source code and it seems geared towards text labels (naturally). Implementing this seems like kind of a big refactor, if I understand the code correctly. I'm going to keep trying at it. I'm getting Doom's ammo sprites from Dae's Fullscreen HUD, which has some purportedly high resolution ammo sprites for this purpose.

![image](https://github.com/Tekkish/AmmoInfo/assets/59481467/04be4b65-adcf-4637-bcc0-68f9a055425a)

**Comment by Tekkish** [comment]
Sorry for the delay in responding to you, I haven't been paying close enough attention to GitHub for these add-ons.

You will likely have trouble with this because, as you said, the code is very much oriented around the text itself. It's used for alignment and spacing as well, so you'll wind up with all sorts of problems when you insert images of varying sizes into the mix. 

Achieving this would require a total rewrite in ZScript, and with a significantly reduced amount of customization. The add-on would then also require additional maintenance for the supported mods. They often do not include their own sprites for some or all of their ammo types, which would mandate the need for manual inclusion after each update.

For now, I'm going to hold off on this, but I may address this in the future if I get around to reworking more of the code in ZScript.

**Comment by mcauley-penney** [comment]
> Sorry for the delay in responding to you

No worries at all!

> Achieving this would require a total rewrite in ZScript, and with a significantly reduced amount of customization

I came to the same conclusion about the degree of customization. Right now, I'm trying to basically use ammoinfo as a jumping off point for exploring ACS and ZScript and writing this myself. In the end, it will only support Doom, little to no customization, no mods that add new weapons, and I won't be posting it for anyone else to use. 

Thanks for the response btw! I'm happy to continue experiment with this myself and I'll keep this issue in mind for any changes in the far future.
